"""fist-migration

Revision ID: d04863a598b5
Revises:
Create Date: 2025-11-14 10:36:02.958314

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d04863a598b5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Enum("ENGLISH", "SPANISH", name="code"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "ELEMENTARY",
                "INTERMEDIATE",
                "UPPER_INTERMEDIATE",
                "ADVANCED",
                name="difficulty",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Enum("FREE", "PREMIUM", "PRO", name="tier"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("billing_period_months", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tier"),
    )
    op.create_table(
        "tokens",
        sa.Column("jti", sa.Integer(), nullable=False),
        sa.Column(
            "renewd_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "ELEMENTARY",
                "INTERMEDIATE",
                "UPPER_INTERMEDIATE",
                "ADVANCED",
                name="difficulty",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="role"), nullable=False),
        sa.Column("pfp", sa.String(), nullable=True),
        sa.Column("day_streak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_email"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index("ix_email", "users", ["email"], unique=False)
    op.create_table(
        "user_languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column(
            "proficiency_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="proficiency_levels"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "language_id", name="uq_user_language"),
    )
    op.create_index("ix_language_id", "user_languages", ["language_id"], unique=False)
    op.create_index("ix_user_languages_id", "user_languages", ["user_id"], unique=False)
    op.create_table(
        "user_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_messages_id", "user_messages", ["user_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("user_message_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "rating",
            sa.Enum("NOVICE", "BEGINNER", "COMPETENT", "PROFICIENT", "EXPERT", name="rate"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["user_message_id"], ["user_messages.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_message", "reports", ["user_message_id"], unique=False)
    op.create_index("ix_user", "reports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user", table_name="reports")
    op.drop_index("ix_message", table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_user_id", table_name="user_messages")
    op.drop_table("user_messages")
    op.drop_index("ix_user_id", table_name="user_languages")
    op.drop_index("ix_language_id", table_name="user_languages")
    op.drop_table("user_languages")
    op.drop_index("ix_email", table_name="users")
    op.drop_table("users")
    op.drop_table("prompts")
    op.drop_table("tokens")
    op.drop_table("subscriptions")
    op.drop_table("languages")
    # ### end Alembic commands ###
